name: Destroy Infrastructure

on:
  workflow_dispatch: # Dispara o workflow apenas manualmente

jobs:
  destroy:
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: sa-east-1

      - name: Terraform Destroy - terraform-rds/avalanches-producao
        run: |
          terraform init -backend-config="bucket=6soat-tfstate" -backend-config="key=terraform-rds/avalanches-producao/terraform.tfstate"
          terraform destroy --auto-approve

      - name: Terraform Destroy - terraform-rds/avalanches-pedido
        run: |
          terraform init -backend-config="bucket=6soat-tfstate" -backend-config="key=terraform-rds/avalanches-pedido/terraform.tfstate"
          terraform destroy --auto-approve

      - name: Terraform Destroy - terraform-eks
        run: |
          terraform init -backend-config="bucket=6soat-tfstate" -backend-config="key=terraform-eks/terraform.tfstate"
          terraform destroy --auto-approve

      - name: Terraform Destroy - terraform-redis
        run: |
          terraform init -backend-config="bucket=6soat-tfstate" -backend-config="key=terraform-redis/terraform.tfstate"
          terraform destroy --auto-approve

      - name: Terraform Destroy - api-gateway
        run: |
          terraform init -backend-config="bucket=6soat-tfstate" -backend-config="key=api-gateway/terraform.tfstate"
          terraform destroy --auto-approve

      - name: Terraform Destroy - avalanches_pagamento/terraform-redis
        run: |
          terraform init -backend-config="bucket=6soat-tfstate" -backend-config="key=avalanches_pagamento/terraform-redis/terraform.tfstate"
          terraform destroy --auto-approve

      - name: Terraform Destroy - avalanches-pedido/terraform-redis
        run: |
          terraform init -backend-config="bucket=6soat-tfstate" -backend-config="key=avalanches-pedido/terraform-redis/terraform.tfstate"
          terraform destroy --auto-approve

      - name: Terraform Destroy - avalanches-pagamento/terraform-redis
        run: |
          terraform init -backend-config="bucket=6soat-tfstate" -backend-config="key=avalanches-pagamento/terraform-redis/terraform.tfstate"
          terraform destroy --auto-approve

      - name: Terraform Destroy - lambda-auth-clientes
        run: |
          terraform init -backend-config="bucket=6soat-tfstate" -backend-config="key=lambda-auth-clientes/terraform.tfstate"
          terraform destroy --auto-approve

      - name: Terraform Destroy - lambda-auth-funcionarios
        run: |
          terraform init -backend-config="bucket=6soat-tfstate" -backend-config="key=lambda-auth-funcionarios/terraform.tfstate"
          terraform destroy --auto-approve

      - name: Terraform Destroy - lambda-cadastro
        run: |
          terraform init -backend-config="bucket=6soat-tfstate" -backend-config="key=lambda-cadastro/terraform.tfstate"
          terraform destroy --auto-approve
